apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: leitor-cluster-binding
subjects:
- kind: ServiceAccount
  name: leitor-global
  namespace: default
roleRef:
  kind: ClusterRole
  name: leitor-cluster
  apiGroup: rbac.authorization.k8s.io
