apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-secret1
  name: nginx-secret1
spec:
  containers:
  - image: nginx
    name: nginx-secret1
    resources: {}
    volumeMounts:
    - name: secret
      mountPath: /data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: secret
    secret:
      secretName: minha-secret 
      items:
      - key: user
        path: usuario.config
