apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "200m" #1/5 de cpu
        memory: "256Mi"
        ephemeral-storage: "1Gi"
      limits:
        cpu: "400m"
        memory: "512Mi"
        ephemeral-storage: "1Gi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
