apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-limit-quota
  name: nginx-limit-quota
spec:
  containers:
  - image: nginx
    name: nginx-limit-quota
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 2
        memory: "128Mi"
      limits:
        cpu: 2
        memory: "256Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
