apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "800Mi" #1/5 de cpu
        memory: "512Mi"
      limits:
        cpu: "1000Mi"
        memory: "512Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
