apiVersion: v1
kind: ResourceQuota
metadata:
  name: ns-quota
spec:
  hard: #Quantidade máxima que vai poder ter 
    cpu: "10"  #Quantidade máxima de request CPU
    memory: "1Gi"
    pods: 10 #1Pod
