apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-front
    version: v1
  name: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-front
      version: v1
  strategy: {}
  template:
    metadata:
      labels:
        app: app-front
        version: v1
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}