apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-30
spec:
  replicas: 5  
  selector:
    matchLabels:
      app: deploy-30
  template:
    metadata:
      labels:
        app: deploy-30
    spec:
      containers:
      - image: nginx
        name: web
        ports:
        - containerPort: 80
        env:
        - name: tier
          value: web
        - name: environment
          value: prod
      - image: busybox
        name: sleep
        command: ["sleep"]
        args: ["3600"]
