apiVersion: v1
kind: Pod
metadata:
  name: ex-cm-pod1
spec:
  containers:
  - image: nginx
    name: ex-36
    ports:
    - containerPort: 80
    volumeMounts:
    - name: env-configs-kubectl
      mountPath: /data
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: env-configs-kubectl
    configMap:
      name: env-configs-kubectl
   
