apiVersion: v1
kind: Pod
metadata:
  name: ex-cm-pod1
spec:
  containers:
  - image: nginx
    name: ex-36
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
        name: env-configs-kubectl
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
