apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ex-secret-pod1
  name: ex-secret-pod1
spec:
  containers:
  - image: nginx
    name: ex-secret-pod1
    ports:
    - containerPort: 80
    envFrom:
    - secretRef: 
        name: user-secret-kubectl 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
#  volumes:
#  - name: secret
#    secret:
#      secretName: user-secret-kubectl
#      items:
#      - key: user
#        path: user.conf
