apiVersion: apps/v1
kind: Deployment
metadata:
  name: primeiro-deploy
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        env:
        - name: env
          value: "xpto4"
        ports:
        - containerPort: 8181
      - args:
        - cat
        - /etc/hosts
        env:
        - name: tier
          value: web
        image: nginx
        name: nginx5
        ports:
        - containerPort: 80
        resources: {}
      - env:
        - name: tier
          value: cache
        image: redis
        name: redis
        ports:
        - containerPort: 6379
