apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: command
  name: command
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - env
    image: nginx
    name: command
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
