apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
    - name: configmap-volume
      mountPath: /data
  
####
#    env:
#    - name: MEUIP
#      valueFrom:
#        configMapKeyRef:
#          name: primeiro-cm
#          key: ip
####
#    envFrom:
#    - configMapRef:
#        name: primeiro-cm
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: configmap-volume
    configMap:
      name: primeiro-cm 
