apiVersion: apps/v1
kind: Deployment
metadata:
  name: primeiro-deploy
spec:
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        env:
        - name: env
          value: "xpto2"
