apiVersion: v1
kind: Service
metadata:
  name: meu-servico-nodeport
spec:
  type: NodePort
  selector:
    run: nginx
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30010
  - port: 8081
    targetPort: 80
    nodePort: 30011